version: "3.7"

services:

  server:
    container_name: server
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports: 
      - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=Production

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"


