version: "3.7"

services:

  server:
    container_name: server
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - redis
      - storage
      - database
    depends_on:
      - redis
      - storage
      - database

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=Development

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  storage:
    container_name: storage
    image: "arafato/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  database:
    container_name: database
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Devp@ssw0rd
    expose:
      - 1433