version: "3.7"

services:

  server:
    container_name: server
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=Development

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  storage:
    container_name: storage
    image: "arafato/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"